apiVersion: apps/v1
kind: Deployment
metadata:
  name: plataforma-front
spec:
  selector:
    matchLabels:
      app: plataforma-front
  template:
    metadata:
      labels:
        app: plataforma-front
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: plataforma-front
          image: registry.fslab.dev/viniciusbraz/plataforma-front
          resources: {}
            
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: plataforma
spec:
  selector:
    app: plataforma-front
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
